server:
  port: 8084
spring:
  datasource:
    username: root
    data-password: 123456
    url: jdbc:mysql://localhost:3306/mmm?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false






